### PR TITLE
renderer: test injectIntoDevTools

### PR DESCRIPTION
**Pull request by raphamorim**
Ref: https://github.com/facebook/react/pull/11463

### CODE REVIEW

**Comment by nitin42** [comment]
I've tested the PR facebook/react#11463 and it is working. Just waiting for the React team to merge this into the `react-reconciler` package. I kinda like this behaviour, put `injectIntoDevTools` directly on `reconciler` instance return value.

**Comment by raphamorim** [comment]
Nice, you made it more faster than me hehe
So, I'll wait for next version of `react-renderer`.

**Comment by nitin42** [comment]
Wait.. I'm giving you the exact production files so you can also test this right now!

**Comment by nitin42** [comment]
Use these files 😄

* react-reconciler (`react-reconciler.development.min.js`) - https://cdn.rawgit.com/nitin42/c1264cc984d94fae350b263ac4ae2991/raw/75e815145fc547ebe1cae77200b55bd9ca350e30/react-reconciler.development.min.js

* react-reconciler(`react-reconciler.production.min.js`) - 
https://cdn.rawgit.com/nitin42/a17af536f53ebb8eefb4abdcac7abba9/raw/6880f0e7f680dbfb1d044a6ab75f2c7970325d7b/react-reconciler.production.min.js

* react-dom(`react-dom.production.min.js`) - 
https://cdn.rawgit.com/nitin42/40e84607c4b5f6a7a7341456fe9597a9/raw/7c55c0b11f56308cecd377e2c39acc74aca03352/react-dom.production.min.js

* react-dom(`react-dom.development.min.js`) -
https://cdn.rawgit.com/nitin42/051eb36b3b4ef9a8ae68c16b6aea4ec9/raw/5886a9846d142b9000f7cdb81fc9032fdafeaaac/react-dom.development.min.js

**Comment by raphamorim** [comment]
Thanks!
I tested it and worked! 👍

**Comment by nitin42** [comment]
Awesome!

**Comment by nitin42** [comment]
Well, the PR has been merged into `react-reconciler` master!

**Comment by raphamorim** [comment]
Nice @nitin42! Thanks for reporting it :D

**Comment by raphamorim** [comment]
Closed by https://github.com/raphamorim/react-tv/pull/123

**Pull request closed without merging**
